# Generated by Django 2.2.8 on 2019-12-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20191202_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='publishedAt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='urlToImage',
            field=models.URLField(null=True),
        ),
    ]
